### ISSUE TITLE
Wait command for frontend availability fails if no pod is running

### ISSUE THREAD

**Issue by danielzozin** [krateoplatformops/krateo-v2-docs#43]
**Describe the bug**
The Krateo installation page indicates a command to wait for frontend after helm chart has been installed.

If frontend pods are not already started the command breaks instead of waiting for pods.

The behaviour is the following:

```
$ kubectl wait --for=condition=Ready $(kubectl get pods --field-selector=status.phase!=Succeeded,status.phase!=Failed --output=name -n krateo-system | grep '^pod/krateo-frontend') -n krateo-system
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'
```

**To Reproduce**
1. Install Krateo with helm
2. Just after the helm chart is installed run the frontend wait command
3. See error

**Expected behavior**
Wait command should wait until the frontend is available

**Screenshots**
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by braghettos** [comment]
Please try with updated info: https://docs.krateo.io/how-to-guides/installing-krateo/#basic-installation
