### ISSUE TITLE
Inaccessible interface after clean installation

### ISSUE THREAD

**Issue by rascasoft** [krateoplatformops/krateo-v2-docs#44]
**Describe the bug**
After installing Krateo with the Helm chart (on a freshly installed Kubernetes with Kind), by following the documentation, the frontend interface shows an error related to the authentication method.

**To Reproduce**
1. Install Krateo using the Helm chart.
2. Expose the frontend so that it can be accessible, as in:
    ```
    $ kubectl -n krateo-system expose service krateo-frontend-x-krateo-system-x-vcluster-k8s --type=LoadBalancer --name=krateo-frontend-x-krateo-system-x-vcluster-k8s-lb
    ```
3. Try to access the interface and you will get "Ops! Something didn't work / Unable to retrieve authentication methods" (see attachment).

**Expected behavior**
A login interface.

**Screenshots**
![image](https://github.com/krateoplatformops/krateo/assets/15247887/bf6a26cf-a315-498e-9534-9463e3e21702)

**Desktop (please complete the following information):**
 - OS: Linux Mint Virginia
 - Browser Firefox
 - Version 125.0.1

**Comment by braghettos** [comment]
Please try with updated info: https://docs.krateo.io/how-to-guides/installing-krateo/#basic-installation, kind section

**Comment by rascasoft** [comment]
I can confirm that by using the kind configuration with the fixed node ports the login page is now showing up (given that missing link pointing to http://172.18.0.2:30080/assets/logo_big-11b390ab.svg):

![image](https://github.com/krateoplatformops/krateo-v2-docs/assets/15247887/5f434cf2-7b0e-4e67-a8e7-3b6bde07b570)

Problem is that I don't feel like imposing a kind configuration based on two nodes and on fixed NodePorts should be considered a solution. Since we're talking about services that are communicating one to another, we should not have fixed links to node ports.

I thing that the interface should work using the NodePort, a LoadBalancer or by even using `kubectl -n krateo-system port-forward krateo-frontend-5dcbcdb7f-687sm-x-krateo-system-x-vcluster-k8s 8080:8080` to directly map the port on my localhost gives the same exact result. Today this does not work:

![krateo-01](https://github.com/krateoplatformops/krateo-v2-docs/assets/15247887/fc09f703-8e51-4bda-82f9-1de3090705d9)

And this was tested with the latest Helm chart as well. I don't think this issue should be closed.
